services:
  backend:
    build: example-backend/
    environment:
      REDIS_HOST: rd-cache
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: example
    container_name: back
  frontend:
    build: example-frontend/
    container_name: front
  redis:
    image: redis
    hostname: rd-cache
  db:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    container_name: db
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

