services:
  backend:
    build: example-backend/
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: rd-cache
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: example
  frontend:
    build: example-frontend/
    ports:
      - 5000:5000
  redis:
    image: redis
    hostname: rd-cache
  db:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    container_name: db

