services:
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.colasloth.com
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /run/user/1338223/docker.sock:/tmp/docker.sock:ro
    ports:
      - 8080:80
