services:
  backend:
    build: example-backend/
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: rd-cache
  frontend:
    build: example-frontend/
    ports:
      - 5000:5000
  redis:
    image: redis
    hostname: rd-cache

